server:
  port: 8002
spring:

  application:
    name: bill-consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}



